<?php require_once "templates/header.phtml" ?>

<div class="form-container">
    <form action="<?= BASE_URL ?>modificarGenero/<?= $genero->id_genero ?>" method="POST" class="my-4">
        <div class="row">
            <div class="col-9">
                <div class="form-group">
                    <label>Modificar nombre</label>
                    <input name="nombre" type="text" class="form-control" value="<?= $genero->nombre ?? '' ?>">
                </div>
            </div>
            <div class="col-9">
                <div class="form-group">
                    <label>Modificar descripción</label>
                    <textarea name="descripcion" class="form-control"><?= $genero->descripcion ?? '' ?></textarea>
                </div>
            </div>
        </div>

        <button type="submit" class="btn btn-primary mt-2">Modificar</button>
    </form>
</div>