<?php require_once("templates/header.phtml") ?>

<div class="form-container">
  <?php if ($Juego && $verify): ?>
    <form action="<?= BASE_URL ?>modificarJuego/<?= $Juego['id_videojuego'] ?>" method="POST" class="my-4">
      
      <div class="row">
        <div class="col-9">
          <div class="form-group">
            <label>Modificar género:</label>
            <select name="id_genero" class="form-control">
              <option value="">Elegir</option>
              <?php foreach ($generos as $genero): ?>
                <option value="<?= $genero->id_genero ?>" <?= $Juego['id_genero'] == $genero->id_genero ? 'selected' : '' ?>>
                  <?= $genero->nombre ?>
                </option>
              <?php endforeach ?>
            </select>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-9">
          <div class="form-group">
            <label>Modificar título</label>
            <input name="titulo" type="text" class="form-control" value="<?= $Juego['titulo'] ?>">
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-9">
          <div class="form-group">
            <label>Modificar año de publicación</label>
            <input name="anio_publicacion" type="number" class="form-control" value="<?= $Juego['anio_publicacion'] ?>">
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-9">
          <div class="form-group">
            <label>Modificar imagen (URL)</label>
            <input name="imagen" type="text" class="form-control" value="<?= $Juego['imagen'] ?>">
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-9">
          <div class="form-group">
            <label>Modificar sinopsis</label>
            <textarea name="sinopsis" class="form-control"><?= $Juego['sinopsis'] ?></textarea>
          </div>
        </div>
      </div>

      <button type="submit" class="btn btn-primary mt-2">Modificar</button>
    </form>
  <?php else: ?>
    <p>No tienes permisos suficientes</p>
  <?php endif; ?>
</div>
