<?php require_once("templates/header.phtml") ?>

<?php if($verify):?>
    <?php require_once("templates/formJuego.phtml") ?>
<?php endif ?>

<div class="form-container">
    <form action="agregarJuego" method="POST" class="my-4">
        
        <div class="row">
            <div class="col-9">
                <div class="form-group">
                    <label>Género:</label>
                    <select name="id_genero" class="form-control">
                        <option value="">Elegir</option>
                        <?php foreach ($generos as $genero): ?>
                            <option value="<?= $genero->id_genero ?>"> <?= $genero->nombre ?> </option>
                        <?php endforeach ?>
                    </select>
                </div>
            </div>
        </div>

        <div class="form-group">
            <label>Título:</label>
            <input type="text" name="titulo" class="form-control">
        </div>

        <div class="form-group">
            <label>Año de publicación:</label>
            <input type="number" name="anio_publicacion" class="form-control">
        </div>

        <div class="form-group">
            <label>Sinopsis:</label>
            <textarea name="sinopsis" class="form-control"></textarea>
        </div>

        <div class="form-group">
            <label>Link de la imagen:</label>
            <input type="text" name="imagen" class="form-control">
        </div>

        <button type="submit" class="btn btn-primary mt-2">Guardar</button>
    </form>
</div>