<?php require_once("templates/header.phtml") ?>

<?php if ($verify): ?>
    <?php require_once("templates/formGeneros.phtml") ?>
<?php endif ?>

<div class="container-listado">
    <table class="table table-dark">
        <thead>
            <tr>
                <th scope="col">Nombre</th>
                <th scope="col">Descripción</th>
                <?php if ($verify): ?>
                    <th scope="col">Acciones</th>
                <?php endif ?>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($generos as $item): ?>
                <tr>
                    <td><?= $item->nombre ?></td>
                    <td><?= $item->descripcion ?></td>
                    <?php if ($verify): ?>
                        <td>
                            <a href="eliminarGenero/<?= $item->id_genero ?>" type='button' class='btn btn-danger'>Eliminar</a>
                            <form action="formModificarGenero/<?= $item->id_genero ?>" method="POST" style="display: inline;">
                                <button type="submit" class="btn btn-success">Modificar</button>
                            </form>
                        </td>
                    <?php endif ?>
                </tr>
            <?php endforeach ?>
        </tbody>
    </table>
</div>
