<?php require_once("templates/header.phtml") ?>
    
<div class="container-listado">
    <table class="table table-dark">
        <thead>
            <tr>
                <th scope="col">Título</th>
                <th scope="col">Ver Detalle</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($Juegos as $juego): ?>
                <tr>
                    <td><?= $juego->titulo ?></td>
                    <td>
                        <a href="mostrarDetalleJuego/<?= $juego->id_videojuego ?>" class="btn btn-primary">Ver Detalle</a>
                    </td>
                </tr>
            <?php endforeach ?>
        </tbody>
    </table>
    <a href="showJuegos" class="btn btn-primary">Back</a>
</div>